export enum Free3DKeys {
    INIT_RECORDER = "INIT_RECORDER",
    ON_INIT_RECORDER = "ON_INIT_RECORDER",
    TRIGGER_RECORD = "TRIGGER_RECORD",
    ON_TRIGGER_RECORD = "ON_TRIGGER_RECORD",
    PREPARE_RECORD = "PREPARE_RECORD",
    ON_PREPARE_RECORD = "ON_PREPARE_RECORD",
    FINISHED_RECORD = "FINISHED_RECORD",
    ON_FINISH_RECORD = "ON_FINISH_RECORD",
    PROCESS_RECORDING = "PROCESS_RECORDING",
    INIT_SUPERVISOR = "INIT_SUPERVISOR",
    ON_INIT_SUPERVISOR = "ON_INIT_SUPERVISOR",
    FINISH_RECORD = "FINISH_RECORD"
}